export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  TICKET_NOT_FOUND: "TICKET_NOT_FOUND",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  RECTIFY_NOTE_REQUIRED: "RECTIFY_NOTE_REQUIRED",
  REJECT_REASON_REQUIRED: "REJECT_REASON_REQUIRED",
  TICKET_ALREADY_CLOSED: "TICKET_ALREADY_CLOSED"
} as const;
