ERROR_CODES = {
    "AUTH_REQUIRED": "AUTH_REQUIRED",
    "RBAC_DENIED": "RBAC_DENIED",
    "VALIDATION_FAILED": "VALIDATION_FAILED",
    "TICKET_NOT_FOUND": "TICKET_NOT_FOUND",
    "INVALID_TICKET_STATE": "INVALID_TICKET_STATE",
    "RECTIFY_NOTE_REQUIRED": "RECTIFY_NOTE_REQUIRED",
    "REVIEW_COMMENT_REQUIRED": "REVIEW_COMMENT_REQUIRED",
    "UNKNOWN_REVIEW_ACTION": "UNKNOWN_REVIEW_ACTION",
}
